APP_BASE_URL = "http://localhost:8501"

sender_email = "retailproplus@gmail.com"
app_password = "ovpdebdmurasuqpz"
smtp_server = "smtp.gmail.com"
smtp_port = 465


GOOGLE_API_KEY = "AIzaSyAP42qpdVf5fKifMLVI2c6JII7djw7Mb4A"

SENDER_APP_PASSWORD = "ivdazgxhjmryxijb"